---
apiVersion: v1
kind: Pod
metadata:
  name: bastionhost
  namespace: default
  labels:
    app: bastionhost
spec:
  # serviceAccountName: gsdb-sa
  containers:
  - name: bh
    image: nnsense/mgmt_bastionhost
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "sleep infinity" ]

    env:
    - name: AWS_ACCESS_KEY_ID
      value: $AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      value: $AWS_SECRET_ACCESS_KEY

